CREATE TABLE its.Org ( 
    id              	BIGINT NOT NULL,
    strParentOrgCode	VARCHAR(50) NOT NULL,
    strOrgNum       	VARCHAR(50) NOT NULL,
    strOrgName      	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_Org PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.Bank ( 
    id          BIGINT NOT NULL,
    strBankCode	VARCHAR(50) NOT NULL,
    strBankName	VARCHAR(150) NOT NULL,
    CONSTRAINT idx_Bank PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.BrunchRegister ( 
    id         	  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strBankCode	  VARCHAR(50) NOT NULL,
    strBankName	  VARCHAR(150) NOT NULL,
    strPanIn   	  VARCHAR(50) NOT NULL,
    strNameIn  	  VARCHAR(100) NOT NULL,
    strPanOut  	  VARCHAR(50) NOT NULL,
	strPanInType  VARCHAR(50) NOT NULL,
	strRouteCode  VARCHAR(50) NOT NULL,
    CONSTRAINT idx_BrunchRegister PRIMARY KEY(id)	
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CardSettleCycleLog ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum   	VARCHAR(50) NOT NULL,
    iTermBatchNo     	BIGINT NOT NULL,
    dtStart          	TIMESTAMP NOT NULL,
    dtEnd            	TIMESTAMP,
    iStatus          	BIGINT NOT NULL,
    iCardSurplusCount	BIGINT NOT NULL,
    iCardRefillCount 	BIGINT NOT NULL,
    CONSTRAINT idx_CardSettleCycleLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CardSettleCycleLogHis ( 
    id               	BIGINT NOT NULL,
    strTerminalNum   	VARCHAR(50) NOT NULL,
    iTermBatchNo     	BIGINT NOT NULL,
    dtStart          	TIMESTAMP NOT NULL,
    dtEnd            	TIMESTAMP,
    iStatus          	BIGINT NOT NULL,
    iCardSurplusCount	BIGINT NOT NULL,
    iCardRefillCount 	BIGINT NOT NULL,
    CONSTRAINT idx_CardSettleCycleLogHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CardTransLog ( 
    id                  	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum      	VARCHAR(50) NOT NULL,
    strTransCode        	VARCHAR(50) NOT NULL,
    strPan              	VARCHAR(50) NOT NULL,
    strIDCardNum        	VARCHAR(50),
    dtOccur             	TIMESTAMP NOT NULL,
    iHostTxStatus       	BIGINT NOT NULL,
    iTermTxStatus       	BIGINT NOT NULL,
    strHostSerialNo     	VARCHAR(50),
    strCardType         	VARCHAR(50) NOT NULL,
    dtHostOccur         	TIMESTAMP,
    iTermBatchNo        	BIGINT NOT NULL,
	iSettleCycleStatus      BIGINT NOT NULL,
    strHostRetCode      	VARCHAR(50),
    strTermSerialNo     	VARCHAR(50) NOT NULL,
    strOrigstrTxSerialNo	VARCHAR(50),
	strSingleBusinessNum	VARCHAR(50),
    strExInfo1          	VARCHAR(150),
    strExInfo2          	VARCHAR(150),
    CONSTRAINT idx_CardTransLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;



CREATE TABLE its.CardTransLogHis ( 
    id                  	BIGINT NOT NULL,
    strTerminalNum      	VARCHAR(50) NOT NULL,
    strTransCode        	VARCHAR(50) NOT NULL,
    strPan              	VARCHAR(50) NOT NULL,
    strIDCardNum        	VARCHAR(50),
    dtOccur             	TIMESTAMP NOT NULL,
    iHostTxStatus       	BIGINT NOT NULL,
    iTermTxStatus       	BIGINT NOT NULL,
    strHostSerialNo     	VARCHAR(50),
    strCardType         	VARCHAR(50) NOT NULL,
    dtHostOccur         	TIMESTAMP,
    iTermBatchNo        	BIGINT NOT NULL,
	iSettleCycleStatus      BIGINT NOT NULL,
    strHostRetCode      	VARCHAR(50),
    strTermSerialNo     	VARCHAR(50) NOT NULL,
    strOrigstrTxSerialNo	VARCHAR(50),
	strSingleBusinessNum	VARCHAR(50),
    strExInfo1          	VARCHAR(150),
    strExInfo2          	VARCHAR(150),
    CONSTRAINT idx_CardTransLogHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CardTypeService ( 
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strCardType   	VARCHAR(50) NOT NULL,
    iServiceMenuId	BIGINT NOT NULL,
    CONSTRAINT idx_CardTypeService PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CardUnitStatus ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum   	VARCHAR(50) NOT NULL,
    iCuNum           	BIGINT NOT NULL,
    strCuType        	VARCHAR(50) NOT NULL,
    iInitialCount    	BIGINT NOT NULL,
    iCurCount        	BIGINT NOT NULL,
    strCuStatus      	VARCHAR(50) NOT NULL,
    strCardType      	VARCHAR(50) NOT NULL,
    strCardTrackStart	VARCHAR(50) NOT NULL,
    strCardTrackEnd  	VARCHAR(50) NOT NULL,
    iCardSuccCount   	BIGINT NOT NULL,
    iCardCaptureCount	BIGINT NOT NULL,
    iCardDestroyCount	BIGINT NOT NULL,
    iCardUnknown     	BIGINT NOT NULL,
    iCardTakenCount  	BIGINT NOT NULL,
    CONSTRAINT idx_CardUnitStatus PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CDSSettleCycleLog ( 
    id              	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum  	VARCHAR(50) NOT NULL,
    iTermBatchNo    	BIGINT NOT NULL,
    dtStart         	TIMESTAMP NOT NULL,
    dtEnd           	TIMESTAMP,
    iStatus         	BIGINT NOT NULL,
    iCDSSurplusCount	BIGINT NOT NULL,
    ICDSREFILLCOUNT 	BIGINT NOT NULL,
    CONSTRAINT idx_CDSSettleCycleLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CDSSettleCycleLogHis ( 
    id              	BIGINT NOT NULL,
    strTerminalNum  	VARCHAR(50) NOT NULL,
    iTermBatchNo    	BIGINT NOT NULL,
    dtStart         	TIMESTAMP NOT NULL,
    dtEnd           	TIMESTAMP,
    iStatus         	BIGINT NOT NULL,
    iCDSSurplusCount	BIGINT NOT NULL,
    ICDSREFILLCOUNT 	BIGINT NOT NULL,
    CONSTRAINT idx_CDSSettleCycleLogHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CDSTransLog ( 
    id                  	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum      	VARCHAR(50) NOT NULL,
    strTransCode        	VARCHAR(50) NOT NULL,
    strOCRNum           	VARCHAR(50),
    strAccountNum       	VARCHAR(50),
    strIDCardNum        	VARCHAR(50),
    dAmt                	DECIMAL(15,2) NOT NULL,
    dtOccur             	TIMESTAMP NOT NULL,
    dFee                	DECIMAL(15,2),
    strAuthIDCardNum    	VARCHAR(50),
    strHostRetCode      	VARCHAR(50),
    iHostTxStatus       	BIGINT NOT NULL,
    iTermTxStatus       	BIGINT NOT NULL,
    strHostSerialNo     	VARCHAR(50),
	strAccMode          	VARCHAR(50),
    strCDSType          	VARCHAR(50),
    dtHostOccur         	TIMESTAMP,
    iTermBatchNo        	BIGINT NOT NULL,
	iSettleCycleStatus      BIGINT NOT NULL,
    strTermSerialNo     	VARCHAR(50) NOT NULL,
    strOrigstrTxSerialNo	VARCHAR(50),
    strSingleBusinessNum	VARCHAR(50) NOT NULL,
	strRate          	    VARCHAR(50),
	strInterest          	VARCHAR(50),
	strTimeLimit          	VARCHAR(50),
    strExInfo1          	VARCHAR(50),
    strExInfo2          	VARCHAR(50),
	strExInfo3          	VARCHAR(50),
	strExInfo4          	VARCHAR(50),
	strExInfo5          	VARCHAR(50),
    CONSTRAINT idx_CDSTransLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CDSTransLogHis ( 
    id                  	BIGINT NOT NULL,
    strTerminalNum      	VARCHAR(50) NOT NULL,
    strTransCode        	VARCHAR(50) NOT NULL,
    strOCRNum           	VARCHAR(50),
    strAccountNum       	VARCHAR(50),
    strIDCardNum        	VARCHAR(50),
    dAmt                	DECIMAL(15,2) NOT NULL,
    dtOccur             	TIMESTAMP NOT NULL,
    dFee                	DECIMAL(15,2),
    strAuthIDCardNum    	VARCHAR(50),
    strHostRetCode      	VARCHAR(50),
    iHostTxStatus       	BIGINT NOT NULL,
    iTermTxStatus       	BIGINT NOT NULL,
    strHostSerialNo     	VARCHAR(50),
	strAccMode          	VARCHAR(50),
    strCDSType          	VARCHAR(50),
    dtHostOccur         	TIMESTAMP,
    iTermBatchNo        	BIGINT NOT NULL,
	iSettleCycleStatus      BIGINT NOT NULL,
    strTermSerialNo     	VARCHAR(50) NOT NULL,
    strOrigstrTxSerialNo	VARCHAR(50),
    strSingleBusinessNum	VARCHAR(50) NOT NULL,
	strRate          	    VARCHAR(50),
	strInterest          	VARCHAR(50),
	strTimeLimit          	VARCHAR(50),
    strExInfo1          	VARCHAR(50),
    strExInfo2          	VARCHAR(50),
	strExInfo3          	VARCHAR(50),
	strExInfo4          	VARCHAR(50),
	strExInfo5          	VARCHAR(50),
    CONSTRAINT idx_CDSTransLogHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;


CREATE TABLE its.CDSUnitStatus ( 
    id              	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum  	VARCHAR(50) NOT NULL,
    iCuNum          	BIGINT NOT NULL,
    strCuType       	VARCHAR(50) NOT NULL,
    iInitialCount   	BIGINT NOT NULL,
    iCurCount       	BIGINT NOT NULL,
    strCuStatus     	VARCHAR(50) NOT NULL,
    strCdsTrackStart	VARCHAR(50) NOT NULL,
    strCdsTrackEnd  	VARCHAR(50) NOT NULL,
    iCdsSuccCount   	BIGINT NOT NULL,
    iCdsCaptureCount	BIGINT NOT NULL,
    iCdsDestroyCount	BIGINT NOT NULL,
    iCdsUnknown     	BIGINT NOT NULL,
    iCdsTakenCount  	BIGINT NOT NULL,
    CONSTRAINT idx_CDSUnitStatus PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.City ( 
    id            	BIGINT NOT NULL,
    strProvinceCode	VARCHAR(50) NOT NULL,
    strCityCode    	VARCHAR(50) NOT NULL,
    strCityName    	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_City PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.DevManu ( 
    id            	BIGINT NOT NULL,
    strDevManuName	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_DevManu PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.DevModel ( 
    id             	BIGINT NOT NULL,
    iDevManuId     	BIGINT NOT NULL,
    strDevModelName	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_DevModel PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.DevModelModule ( 
    id         	BIGINT NOT NULL,
    iDevModelId	BIGINT NOT NULL,
    iModuleId  	BIGINT NOT NULL,
    CONSTRAINT idx_DevModelModule PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.DevType ( 
    id            	BIGINT NOT NULL,
    strDevTypeName	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_DevType PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.ExpLog ( 
    id            	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum	VARCHAR(50) NOT NULL,
    strPan        	VARCHAR(50),
    strExpCode    	VARCHAR(50) NOT NULL,
    dtOccur       	TIMESTAMP,
    strMemo       	VARCHAR(150),
    CONSTRAINT idx_ExpLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.HostRetCode ( 
    id            	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strHostRetCode	VARCHAR(50) NOT NULL,
    strHostRetDesc	VARCHAR(150) NOT NULL,
    CONSTRAINT idx_HostRetCode PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.Misc ( 
    id       	BIGINT NOT NULL,
    strName  	VARCHAR(50) NOT NULL,
    strValue 	VARCHAR(150) NOT NULL,
    strDesc  	VARCHAR(150) NOT NULL,
    strOrgNum	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_Misc PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.Module ( 
    id            	BIGINT NOT NULL,
    strModuleName 	VARCHAR(50) NOT NULL,
    strModuleClsid	VARCHAR(50) NOT NULL,
    strModuleDesc 	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_Module PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.OtherTransLog ( 
    id                  	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum      	VARCHAR(50) NOT NULL,
    strTransCode        	VARCHAR(50) NOT NULL,
    strPan              	VARCHAR(50) NOT NULL,
    strDestPan          	VARCHAR(50) NOT NULL,
    dAmt                	DECIMAL(15,2),
    strCurrency         	VARCHAR(50) NOT NULL,
    dFee                	DECIMAL(15,2),
    strIDCardNum        	VARCHAR(50),
    dtOccur             	TIMESTAMP NOT NULL,
    iHostTxStatus       	BIGINT NOT NULL,
    strHostSerialNo     	VARCHAR(50),
    strCardType         	VARCHAR(50),
    dtHostOccur         	TIMESTAMP,
    iTermBatchNo        	BIGINT NOT NULL,
    strHostRetCode      	VARCHAR(50),
    strTermSerialNo     	VARCHAR(50) NOT NULL,
    iCheckFlag          	BIGINT NOT NULL,
    strOrigstrTxSerialNo	VARCHAR(50),
	strSingleBusinessNum	VARCHAR(50),
    strExInfo1          	VARCHAR(50),
    strExInfo2          	VARCHAR(50),
    iReverseStatus      	BIGINT,
    CONSTRAINT idx_OtherTransLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.OtherTransLogHis ( 
    id                  	BIGINT NOT NULL,
    strTerminalNum      	VARCHAR(50) NOT NULL,
    strTransCode        	VARCHAR(50) NOT NULL,
    strPan              	VARCHAR(50) NOT NULL,
    strDestPan          	VARCHAR(50) NOT NULL,
    dAmt                	DECIMAL(15,2),
    strCurrency         	VARCHAR(50) NOT NULL,
    dFee                	DECIMAL(15,2),
    strIDCardNum        	VARCHAR(50),
    dtOccur             	TIMESTAMP NOT NULL,
    iHostTxStatus       	BIGINT NOT NULL,
    strHostSerialNo     	VARCHAR(50),
    strCardType         	VARCHAR(50),
    dtHostOccur         	TIMESTAMP,
    iTermBatchNo        	BIGINT NOT NULL,
    strHostRetCode      	VARCHAR(50),
    strTermSerialNo     	VARCHAR(50) NOT NULL,
    iCheckFlag          	BIGINT NOT NULL,
    strOrigstrTxSerialNo	VARCHAR(50),
	strSingleBusinessNum	VARCHAR(50),
    strExInfo1          	VARCHAR(50),
    strExInfo2          	VARCHAR(50),
    iReverseStatus      	BIGINT,
    CONSTRAINT idx_OtherTransLogHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;


CREATE TABLE its.Province ( 
    id            	BIGINT NOT NULL,
    strProvinceCode	VARCHAR(50) NOT NULL,
    strProvinceName	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_Province PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.RouteBank ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strRouteCode     	VARCHAR(50) NOT NULL,
    strBankCode      	VARCHAR(50) NOT NULL,
    strBankName      	VARCHAR(150) NOT NULL,
    strBankType      	VARCHAR(50),
    strBankTypeCode  	VARCHAR(50),
    strSettleBankCode	VARCHAR(50),
    strCCPCCode      	VARCHAR(50),
    strSizeMark      	VARCHAR(50),
    CONSTRAINT idx_RouteBank PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.ServiceMenu ( 
    id                  	BIGINT NOT NULL,
    iServiceMenuId      	BIGINT NOT NULL,
    strServiceMenuName  	VARCHAR(50) NOT NULL,
    strServiceMenuNameEn	VARCHAR(50) NOT NULL,
    iBtnPos             	BIGINT NOT NULL,
    iServiceMenuType    	BIGINT NOT NULL,
    strServiceMenuAction	VARCHAR(50) NOT NULL,
    strOrgNum           	VARCHAR(50) NOT NULL,
	strCardType           	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_ServiceMenu PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.TemplateMenu ( 
    id             	BIGINT NOT NULL,
    strTemplateName	VARCHAR(50) NOT NULL,
    strDescription 	VARCHAR(150),
    CONSTRAINT idx_TemplateMenu PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.TemplateMenuRelation ( 
    id            	BIGINT NOT NULL,
    iTemplateId   	BIGINT NOT NULL,
    iServiceMenuId	BIGINT NOT NULL,
    CONSTRAINT idx_TemplateMenuRelation PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.Terminal ( 
    id              	BIGINT NOT NULL,
    strTerminalNum  	VARCHAR(50) NOT NULL,
    strOrgNum       	VARCHAR(50) NOT NULL,
    strNetAddr      	VARCHAR(50) NOT NULL,
    strTellerNum    	VARCHAR(50) NOT NULL,
    iStatus         	BIGINT NOT NULL DEFAULT 0,
    strTerminalStyle	VARCHAR(50) NOT NULL,
    strTerminalAddr 	VARCHAR(50),
    strDevSn        	VARCHAR(50),
    iDevType        	BIGINT NOT NULL,
    strParentOrgNum 	VARCHAR(50),
    iDevModel       	BIGINT NOT NULL,
    iDevManu        	BIGINT NOT NULL,
    dtStart         	TIMESTAMP NOT NULL,
    dtEnd           	TIMESTAMP,
    strMemo         	VARCHAR(500),
    CONSTRAINT idx_Terminal PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.TerminalModule ( 
    id         	BIGINT NOT NULL,
    iTerminalId	BIGINT NOT NULL,
    iModuleId  	BIGINT NOT NULL,
	iModuleFlag BIGINT NOT NULL,
    CONSTRAINT idx_TerminalModule PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;



CREATE TABLE its.TerminalService ( 
    id            	BIGINT NOT NULL,
    iTerminalId   	BIGINT NOT NULL,
    iTemplateId	    BIGINT NOT NULL,
    CONSTRAINT idx_TerminalService PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.Trial ( 
    id         	        BIGINT NOT NULL,
    strTerminalNum   	VARCHAR(50) NOT NULL,
    CONSTRAINT idx_Trial PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.UKeySettleCycleLog ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum   	VARCHAR(50) NOT NULL,
    iTermBatchNo     	BIGINT NOT NULL,
    dtStart          	TIMESTAMP NOT NULL,
    dtEnd            	TIMESTAMP,
    iStatus          	BIGINT NOT NULL,
    iUKeySurplusCount	BIGINT NOT NULL,
    iUKeyRefillCount 	BIGINT NOT NULL,
    CONSTRAINT idx_UKeySettleCycleLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.UKeySettleCycleLogHis ( 
    id               	BIGINT NOT NULL,
    strTerminalNum   	VARCHAR(50) NOT NULL,
    iTermBatchNo     	BIGINT NOT NULL,
    dtStart          	TIMESTAMP NOT NULL,
    dtEnd            	TIMESTAMP,
    iStatus          	BIGINT NOT NULL,
    iUKeySurplusCount	BIGINT NOT NULL,
    iUKeyRefillCount 	BIGINT NOT NULL,
    CONSTRAINT idx_UKeySettleCycleLogHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;



CREATE TABLE its.UKeyTransLog ( 
    id                  	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum      	VARCHAR(50) NOT NULL,
    strTransCode        	VARCHAR(50) NOT NULL,
    strUKeyNum          	VARCHAR(50) NOT NULL,
    strIDCardNum        	VARCHAR(50),
    strBindCardNum      	VARCHAR(50),
    dtOccur             	TIMESTAMP NOT NULL,
    iHostTxStatus       	BIGINT NOT NULL,
    iTermTxStatus       	BIGINT NOT NULL,
    strHostSerialNo     	VARCHAR(50),
    strUKeyType         	VARCHAR(50) NOT NULL,
    dtHostOccur         	TIMESTAMP,
    iTermBatchNo        	BIGINT NOT NULL,
	iSettleCycleStatus      BIGINT NOT NULL,
    strHostRetCode      	VARCHAR(50),
    strTermSerialNo     	VARCHAR(50) NOT NULL,
    strOrigstrTxSerialNo	VARCHAR(50),
	strSingleBusinessNum	VARCHAR(50),
    strExInfo1          	VARCHAR(50),
    strExInfo2          	VARCHAR(50),
    CONSTRAINT idx_UKeyTransLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;



CREATE TABLE its.UKeyTransLogHis ( 
    id                  	BIGINT NOT NULL,
    strTerminalNum      	VARCHAR(50) NOT NULL,
    strTransCode        	VARCHAR(50) NOT NULL,
    strUKeyNum          	VARCHAR(50) NOT NULL,
    strIDCardNum        	VARCHAR(50),
    strBindCardNum      	VARCHAR(50),
    dtOccur             	TIMESTAMP NOT NULL,
    iHostTxStatus       	BIGINT NOT NULL,
    iTermTxStatus       	BIGINT NOT NULL,
    strHostSerialNo     	VARCHAR(50),
    strUKeyType         	VARCHAR(50) NOT NULL,
    dtHostOccur         	TIMESTAMP,
    iTermBatchNo        	BIGINT NOT NULL,
    iSettleCycleStatus      BIGINT NOT NULL,
    strHostRetCode      	VARCHAR(50),
    strTermSerialNo     	VARCHAR(50) NOT NULL,
    strOrigstrTxSerialNo	VARCHAR(50),
	strSingleBusinessNum	VARCHAR(50),
    strExInfo1          	VARCHAR(50),
    strExInfo2          	VARCHAR(50),
    CONSTRAINT idx_UKeyTransLogHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;


CREATE TABLE its.UKeyUnitStatus ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum   	VARCHAR(50) NOT NULL,
    iCuNum           	BIGINT NOT NULL,
    strCuType        	VARCHAR(50) NOT NULL,
    iInitialCount    	BIGINT NOT NULL,
    iCurCount        	BIGINT NOT NULL,
    strCuStatus      	VARCHAR(50) NOT NULL,
    strUKeyType      	VARCHAR(50) NOT NULL,
    strUKeyTrackStart	VARCHAR(50) NOT NULL,
    strUKeyTrackEnd  	VARCHAR(50) NOT NULL,
    iUKeySuccCount   	BIGINT NOT NULL,
    iUKeyCaptureCount	BIGINT NOT NULL,
    iUKeyDestroyCount	BIGINT NOT NULL,
    iUKeyUnknown     	BIGINT NOT NULL,
    iUKeyTakenCount  	BIGINT NOT NULL,
    CONSTRAINT idx_UKeyUnitStatus PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.PadCheck ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum   	VARCHAR(50) NOT NULL,
	strTransCode        VARCHAR(50),
	strCheckSerialNo    VARCHAR(50),
    strbusinessCode     VARCHAR(50),
	strbusinessName     VARCHAR(50),
	strBatchId          VARCHAR(50),
	strCustomNo         VARCHAR(50),
	strCustManagerNo    VARCHAR(50),
	strCustManagerName  VARCHAR(50),
    iStatus    	        BIGINT NOT NULL,
    dtStart         	TIMESTAMP NOT NULL,
    dtEnd           	TIMESTAMP,
	strMemo             VARCHAR(300),
    CONSTRAINT idx_PadCheck PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.FlushData ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strPan   	        VARCHAR(50),
	strTransCode        VARCHAR(50),
	dAmount             DECIMAL(15,2),
	strDestPan          VARCHAR(50),
	strTrack2           VARCHAR(100),
	strTrack3           VARCHAR(300),
	strTerminalNum      VARCHAR(50),
	strEncrypType       VARCHAR(50),
	strPinBlock         VARCHAR(50),
	strField55          VARCHAR(800),
	strField57          VARCHAR(800),
	strOrgTsn           VARCHAR(50),
    iFlushTimes    	    BIGINT,
    CONSTRAINT idx_FlushData PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


CREATE TABLE its.BranchMap ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strLocalRouteCode   VARCHAR(50) NOT NULL,
	strLocalBankCode    VARCHAR(50) NOT NULL,
    CONSTRAINT idx_BranchMap PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;


--add 2017.12.07
--终端批次表
DROP TABLE its.SettleCycleLog;
CREATE TABLE its.SettleCycleLog ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum   VARCHAR(50) NOT NULL,
	isettlecycle     INTEGER NOT NULL,
	dtStart          TIMESTAMP NOT NULL,
	dtEnd            TIMESTAMP,
	isStatus         SMALLINT NOT NULL,
	dCDMSurplusAmt   DECIMAL(15,2) NOT NULL,
	dCIMSurplusAmt   DECIMAL(15,2) NOT NULL,
	dCDMAddAmt       DECIMAL(15,2) NOT NULL,
	strExInfo1         VARCHAR(150),
	strExInfo2         VARCHAR(150),
    CONSTRAINT idx_SettleCycleLog PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;

DROP TABLE its.SettleCycleLogHis;
CREATE TABLE its.SettleCycleLogHis ( 
   id               	BIGINT NOT NULL,
    strTerminalNum   VARCHAR(50) NOT NULL,
	isettlecycle     INTEGER NOT NULL,
	dtStart          TIMESTAMP NOT NULL,
	dtEnd            TIMESTAMP,
	isStatus         SMALLINT NOT NULL,
	dCDMSurplusAmt   DECIMAL(15,2) NOT NULL,
	dCIMSurplusAmt   DECIMAL(15,2) NOT NULL,
	dCDMAddAmt       DECIMAL(15,2) NOT NULL,
	strExInfo1         VARCHAR(150),
	strExInfo2         VARCHAR(150),
    CONSTRAINT idx_SettleCycleLogHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;

--存款交易流水表
DROP TABLE its.TransLogDeposit;
CREATE TABLE its.TransLogDeposit ( 
    id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum   VARCHAR(50) NOT NULL,
	strTransCode     VARCHAR(50) NOT NULL,
	dtOccur		     TIMESTAMP NOT NULL,
	strPan           VARCHAR(50),
	dAmount          DECIMAL(15,2),
	dFee             DECIMAL(15,2),
	iHostTransStatus SMALLINT,
	strHostRetCode   VARCHAR(50) NOT NULL,
	strHostTsn       VARCHAR(50),
	iTermTransStatus  SMALLINT,
	strTermSerialNo  VARCHAR(50) NOT NULL,  
	iSettleCycle     INTEGER,
	iSettleCycleStatus SMALLINT,
	strSingleBusinessNum	VARCHAR(50),
	strExInfo1         VARCHAR(150),
	strExInfo2         VARCHAR(150),
	strExInfo3         VARCHAR(150),
	strExInfo4         VARCHAR(150),
	strExInfo5         VARCHAR(150),	
    CONSTRAINT idx_TransLogDeposit PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;

DROP TABLE its.TransLogDepositHis;
CREATE TABLE its.TransLogDepositHis ( 
    id               	BIGINT NOT NULL,
    strTerminalNum   VARCHAR(50) NOT NULL,
	strTransCode     VARCHAR(50) NOT NULL,
	dtOccur		     TIMESTAMP NOT NULL,
	strPan           VARCHAR(50),
	dAmount          DECIMAL(15,2),
	dFee             DECIMAL(15,2),
	iHostTransStatus SMALLINT,
	strHostRetCode   VARCHAR(50) NOT NULL,
	strHostTsn       VARCHAR(50),
	iTermTransStatus  SMALLINT,
	strTermSerialNo  VARCHAR(50) NOT NULL,  
	iSettleCycle     INTEGER,
	iSettleCycleStatus SMALLINT,
	strSingleBusinessNum	VARCHAR(50),
	strExInfo1         VARCHAR(150),
	strExInfo2         VARCHAR(150),
	strExInfo3         VARCHAR(150),
	strExInfo4         VARCHAR(150),
	strExInfo5         VARCHAR(150),	
    CONSTRAINT idx_TransLogDepositHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;

--取款流水表
DROP TABLE  its.TransLogWithdrawal;
CREATE TABLE its.TransLogWithdrawal ( 
  id               	BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20) NOT NULL,
    strTerminalNum   VARCHAR(50) NOT NULL,
	strTransCode     VARCHAR(50) NOT NULL,
	dtOccur		     TIMESTAMP NOT NULL,
	strPan           VARCHAR(50),
	dAmount          DECIMAL(15,2),
	dFee             DECIMAL(15,2),
	iHostTransStatus SMALLINT,
	strHostRetCode   VARCHAR(50) NOT NULL,
	strHostTsn       VARCHAR(50),
	iTermTransStatus  SMALLINT,
	strTermSerialNo  VARCHAR(50) NOT NULL,  
	iSettleCycle     INTEGER,
	iSettleCycleStatus SMALLINT,
	strSingleBusinessNum	VARCHAR(50),
	iReverSeenTryStatus SMALLINT,
	strExInfo1         VARCHAR(150),
	strExInfo2         VARCHAR(150),
	strExInfo3         VARCHAR(150),
	strExInfo4         VARCHAR(150),
	strExInfo5         VARCHAR(150),	
    CONSTRAINT idx_TransLogWithdrawal PRIMARY KEY(id)
)
IN ITS_DATA16K1
INDEX IN ITS_IDX16K1;

DROP TABLE its.TransLogWithdrawalHis;
CREATE TABLE its.TransLogWithdrawalHis ( 
    id               	BIGINT NOT NULL,
    strTerminalNum   VARCHAR(50) NOT NULL,
	strTransCode     VARCHAR(50) NOT NULL,	
	dtOccur		     TIMESTAMP NOT NULL,
	strPan           VARCHAR(50),
	dAmount          DECIMAL(15,2),
	dFee             DECIMAL(15,2),
	iHostTransStatus SMALLINT,
	strHostRetCode   VARCHAR(50) NOT NULL,
	strHostTsn       VARCHAR(50),
	iTermTransStatus  SMALLINT,
	strTermSerialNo  VARCHAR(50) NOT NULL,  
	iSettleCycle     INTEGER,
	iSettleCycleStatus SMALLINT,
	strSingleBusinessNum	VARCHAR(50),
	iReverSeenTryStatus SMALLINT,
	strExInfo1         VARCHAR(150),
	strExInfo2         VARCHAR(150),
	strExInfo3         VARCHAR(150),
	strExInfo4         VARCHAR(150),
	strExInfo5         VARCHAR(150),	
    CONSTRAINT idx_TransLogWithdrawalHis PRIMARY KEY(id)
)
IN ITS_DATA16K2
INDEX IN ITS_IDX16K1;
